### ISSUE TITLE
kauf-plf12-minimal.yaml not updated for breaking change in ESPHome 2024.6.0

### ISSUE THREAD

**Issue by neillbell** [KaufHA/PLF12#37]
ESPHome 2024.6.0 includes a change that requires a "platform: esphome" statement when configuring OTA. The PLF10 YAML files that PLF12 depends on have been updated to reflect this, but the standalone kauf-plf12-minimal.yaml has not.

Using the current kauf-plf12-minimal.yaml causes an error on validation:

`Failed config`

`At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality`

A workaround is to make a local copy of kauf-plf12-minimal.yaml in esphome/packages and change

`ota:              # https://esphome.io/components/ota.html`

to

`ota:              # https://esphome.io/components/ota.html`
`  package: esphome`

**Comment by bkaufx** [comment]
Fixed it for you.  Sorry.  You'll probably have to wait 24 hours for esphome to check for an updated package or delete the .esphome/packages folder.  Cleaning build files might work.
