### ISSUE TITLE
Some GPIO items in kauf-plf12-minimal.yaml are not properly referenced using substitutions.

### ISSUE THREAD

**Issue by neillbell** [KaufHA/PLF12#5]
The status_led, button binary sensor, blue LED switch and relay switch use GPIO* symbols instead of the appropriate substitions.

**Comment by KaufHA** [comment]
Thanks.  Fixed.  You'll probably need to delete .esphome/packages folder to get ESPHome dashboard to redownload immediately.

**Comment by neillbell** [comment]
It looks like you didn't use a dollar sign on the substitutions.

**Comment by bkaufx** [comment]
Wow, geez.  Fixed it again and made sure it compiled this time.

**Comment by neillbell** [comment]
Works great. Thanks for the quick fix.

I really love the product. It's great to use an IoT device that is not just a black box.
